# Usa Ubuntu como base
FROM ubuntu:latest

# Instala Python y herramientas necesarias
RUN apt update && apt install -y python3 python3-pip python3-venv

# Crea un entorno virtual y activa las dependencias
RUN python3 -m venv /venv
RUN /venv/bin/pip install pycryptodome numpy pillow matplotlib

# Usa el entorno virtual como predeterminado
ENV PATH="/venv/bin:$PATH"

CMD ["python3"]
